"""Your message here

Revision ID: 5fc16dfbce3c
Revises: 9752028359bb
Create Date: 2024-06-19 08:55:11.163444

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5fc16dfbce3c'
down_revision = '9752028359bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
